//! ffmpeg's structs, as its headers lay them out.
//!
//! Generated by `tools/ffmpeg-bindings` against the headers of the build the
//! installer ships, types only: the functions are found by name at run time
//! (see `api`), so nothing here links to ffmpeg. Regenerate it whenever that
//! build's major versions change -- a field moved in a struct is a crash, not
//! a compile error.

#![allow(
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case,
    dead_code,
    unnecessary_transmutes,
    clippy::all
)]

use std::ffi::{c_int, c_void};

include!("ffmpeg_types.rs");

/// `AV_NOPTS_VALUE`, a cast in the header that bindgen cannot see through.
pub const AV_NOPTS_VALUE: i64 = i64::MIN;
/// `AVERROR_EOF`: `-MKTAG('E', 'O', 'F', ' ')`.
pub const AVERROR_EOF: c_int = -0x2046_4F45;
/// `AVERROR(EAGAIN)`: the decoder wants more input before it has a frame.
pub const AVERROR_EAGAIN: c_int = -11;

/// `AVD3D11VADeviceContext`, by hand: its header pulls in all of `d3d11.h`,
/// and every field it has is a COM pointer or a flag word.
#[repr(C)]
pub struct AVD3D11VADeviceContext {
    pub device: *mut c_void,
    pub device_context: *mut c_void,
    pub video_device: *mut c_void,
    pub video_context: *mut c_void,
    pub lock: Option<unsafe extern "C" fn(*mut c_void)>,
    pub unlock: Option<unsafe extern "C" fn(*mut c_void)>,
    pub lock_ctx: *mut c_void,
    pub bind_flags: u32,
    pub misc_flags: u32,
}
