"""Generates the standard-emoji table from Mattermost's own source of truth.

`model.SystemEmojis` in the Mattermost server's public model package maps every
standard emoji name to its codepoint sequence. It is itself generated (by their
`make_emojis.mjs`) from emoji-datasource, and it is what the server uses to
validate reaction names -- so a table generated from it agrees with the server
by construction, including the 2130 skin-tone spellings, 903 hyphenated aliases
and 261 flags that a hand-written table will never keep up with.

    python tools/generate_emoji_table.py

Writes `crates/matterless-render/src/emoji_table.rs`. Re-run it when the server
is upgraded; the generated file is committed so a build needs no network.
"""

import datetime
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(ROOT)
SOURCE = (
    "https://raw.githubusercontent.com/mattermost/mattermost/master"
    "/server/public/model/emoji_data.go"
)
OUT = os.path.join(REPO, "crates", "matterless-render", "src", "emoji_table.rs")
ENTRY = re.compile(r'"([^"]+)":\s*"([0-9a-f\-]+)"')


def main():
    # The date is enough to tell a stale table from a fresh one: the standard
    # set only changes when the server is upgraded.
    stamp = datetime.date.today().isoformat()
    print("fetching", SOURCE)
    with urllib.request.urlopen(SOURCE, timeout=120) as response:
        source = response.read().decode("utf-8")

    pairs = ENTRY.findall(source)
    if len(pairs) < 3000:
        raise SystemExit(f"only {len(pairs)} entries parsed -- the format may have changed")

    # Sorted, because the lookup is a binary search.
    table = sorted(dict(pairs).items())
    print(f"{len(table)} names")

    with open(OUT, "w", encoding="utf-8", newline="\n") as out:
        out.write(
            "// Generated by `tools/generate_emoji_table.py` -- do not edit by hand.\n"
            "//\n"
            "// Source: Mattermost's `model.SystemEmojis`\n"
            f"// ({SOURCE}),\n"
            "// itself generated from emoji-datasource (MIT). This is the map the server\n"
            "// uses to validate reaction names, so the client agrees with it by\n"
            "// construction rather than by measurement.\n"
            "//\n"
            "// Name to codepoint sequence, sorted by name for binary search. Codepoints\n"
            "// rather than characters because that is the server's own spelling of them,\n"
            "// and because `/static/emoji/<codepoints>.png` is a real route if a font ever\n"
            "// lacks a glyph.\n"
            "//\n"
            "// The generation date is recorded so a server upgrade -- the only thing\n"
            "// that changes the standard set -- shows up in the log rather than as a\n"
            "// stray `:name:` somebody has to notice.\n"
            f'pub static GENERATED_ON: &str = "{stamp}";\n'
            f"pub static SYSTEM_EMOJI: [(&str, &str); {len(table)}] = [\n"
        )
        for name, codepoints in table:
            out.write(f'    ("{name}", "{codepoints}"),\n')
        out.write("];\n")

    print("wrote", OUT)


if __name__ == "__main__":
    main()
