"""Generates the standard emoji's categories, for the reaction picker's tabs.

`emoji_table.rs` answers "what does `:name:` draw as" and is generated from the
server's own `model.SystemEmojis`, which carries no categories at all. Browsing
needs them, so they come from emoji-data (MIT) -- the same dataset Mattermost's
webapp uses, which is why the tabs here read the way they do in every other
client.

Only names the table already knows are kept: the picker must never offer a
reaction the renderer cannot draw. That also drops the skin-tone variants and
hyphenated aliases, which belong in `:name:` completion and not in a grid.

Run it the way `generate_emoji_table.py` is run; it writes
`crates/matterless-render/src/emoji_categories.rs`.
"""

import datetime
import json
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(ROOT)
SOURCE = "https://raw.githubusercontent.com/iamcal/emoji-data/master/emoji.json"
TABLE = os.path.join(REPO, "crates", "matterless-render", "src", "emoji_table.rs")
OUT = os.path.join(REPO, "crates", "matterless-render", "src", "emoji_categories.rs")

# The order every other client shows them in, faces first. `Component` is
# skin-tone modifiers, which are not emoji anybody reacts with.
ORDER = [
    ("Smileys & Emotion", "Smileys"),
    ("People & Body", "People"),
    ("Animals & Nature", "Nature"),
    ("Food & Drink", "Food"),
    ("Activities", "Activities"),
    ("Travel & Places", "Travel"),
    ("Objects", "Objects"),
    ("Symbols", "Symbols"),
    ("Flags", "Flags"),
]

KNOWN = re.compile(r'\("([^"]+)",\s*"[0-9a-f\-]+"\)')


def main():
    stamp = datetime.date.today().isoformat()

    with open(TABLE, encoding="utf-8") as handle:
        known = set(KNOWN.findall(handle.read()))
    if len(known) < 3000:
        raise SystemExit(f"only {len(known)} names read from {TABLE} -- generate it first")
    print(f"{len(known)} names in the table")

    print("fetching", SOURCE)
    with urllib.request.urlopen(SOURCE, timeout=120) as response:
        data = json.loads(response.read().decode("utf-8"))
    if len(data) < 1500:
        raise SystemExit(f"only {len(data)} entries -- the format may have changed")

    grouped = {}
    for entry in data:
        category = entry.get("category")
        if category not in dict(ORDER):
            continue
        # `short_names` first, because the table's spelling is not always the
        # dataset's preferred one.
        name = next((n for n in entry.get("short_names", []) if n in known), None)
        if name is None:
            continue
        grouped.setdefault(category, []).append((entry.get("sort_order", 0), name))

    total = 0
    with open(OUT, "w", encoding="utf-8", newline="\n") as out:
        out.write(
            "// Generated by `tools/generate_emoji_categories.py` -- do not edit by hand.\n"
            "//\n"
            "// Source: emoji-data (MIT)\n"
            f"// ({SOURCE}), the dataset Mattermost's own webapp categorises by -- so\n"
            "// these tabs read the way they do in every other client.\n"
            "//\n"
            "// Only names `emoji_table.rs` knows are listed: the picker must never offer\n"
            "// a reaction the renderer cannot draw. Skin-tone variants and hyphenated\n"
            "// aliases fall out of that rule, which is right -- they belong in `:name:`\n"
            "// completion, not in a grid.\n"
            "//\n"
            "// Within a category the dataset's own `sort_order` is kept: it is the order\n"
            "// a reader expects to find them in, faces before hands before hearts.\n"
            f'pub static CATEGORIES_GENERATED_ON: &str = "{stamp}";\n'
            f"pub static EMOJI_CATEGORIES: [(&str, &[&str]); {len(ORDER)}] = [\n"
        )
        for category, label in ORDER:
            names = [name for _, name in sorted(grouped.get(category, []))]
            total += len(names)
            print(f"{len(names):5d}  {label}")
            out.write(f'    ("{label}", &[\n')
            for name in names:
                out.write(f'        "{name}",\n')
            out.write("    ]),\n")
        out.write("];\n")

    print(f"wrote {OUT} -- {total} names in {len(ORDER)} categories")


if __name__ == "__main__":
    main()
